// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechicalTask.API.Data;

#nullable disable

namespace TechicalTask.API.Migrations
{
    [DbContext(typeof(ClientsDBContext))]
    [Migration("20230423161306_init1")]
    partial class init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechicalTask.API.Classes.Client", b =>
                {
                    b.Property<string>("X_Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("str")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("X_Name");

                    b.ToTable("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
